# deploy using `gcloud app deploy`
runtime: nodejs14 # or whatever version of Node.js you're using

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6

env_variables:
  CLERK_SECRET_KEY: "sk_test_h1l7ukagcJtS4ys3TLNRYYTzIvVwlOp1pvxX5b7L7E"
  DB_USER: "postgres"
  DB_HOST: "db.htnkbjjakwynjxocwsll.supabase.co"
  DB_NAME: "postgres"
  DB_PASSWORD: "7mUMCMFCAw4Cc2bc"
  DB_PORT: "6543"
