import Head from "next/head";
import Image from "next/image";
import React, { useState } from "react";
import Link from "next/link";
import { CircleNotch, CheckCircle } from "@phosphor-icons/react";

export default function Login() {
  const [email, setEmail] = useState("");
  const [errorMessage, setErrorMessage] = useState("");
  const [loading, setLoading] = useState(false); // Add this line
  const [emailSent, setEmailSent] = useState(false); // Add this line

  const sendEmailWithDelay = async (email: string) => {
    await Promise.all([
      new Promise<void>((resolve) => {
        setTimeout(() => {
          setLoading(false); // Set loading back to false after the delay
          resolve();
        }, 1500);
      }),
      new Promise<void>((resolve) => {
        // Call mock API to send email here
        console.log("Email sent to", email);
        resolve();
      }),
    ]);
    setEmailSent(true); // Set emailSent to true after both Promises have resolved
  };

  // Handle Sign up
  const handleSubmit = async (event: any) => {
    event.preventDefault();
    console.log("Password reset data:", { email });
    // Here you can send the form data to your backend or perform any other necessary action.
    setEmailSent(false); // Reset emailSent to false
    setErrorMessage("");
    if (!email) {
      setErrorMessage("Email is required.");
      return;
    }

    const emailRegex = /^[\w-]+(\.[\w-]+)*@([\w-]+\.)+[a-zA-Z]{2,7}$/;
    if (!emailRegex.test(email)) {
      setErrorMessage("Please enter a valid email address.");
      return;
    }

    setLoading(true); // Set loading to true before the delay
    await sendEmailWithDelay(email);
  };

  return (
    <>
      <Head>
        <title>Dataland</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>
      <main
        className={`overflow-hidden flex h-screen flex-row justify-center items-center min-h-screen bg-slate-1`}
      >
        <div className="w-full flex flex-row flex-grow h-screen">
          <div className="w-full flex justify-center border-r border-slate-3">
            <div className="w-[600px] text-white flex flex-col pt-40 left-0 py-3 gap-2 sm:px-24 px-12 h-screen">
              <header className="fixed top-8">
                <Link href="/">
                  <Image
                    src="/images/logo_darker.svg"
                    width={80}
                    height={32}
                    alt="Dataland logo"
                  ></Image>
                </Link>
              </header>
              <h1 className="text-xl ">Home</h1>
              <h3 className="text-[14px] text-slate-11">
                We&apos;ll email you a link to reset your password.
              </h3>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
