import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import InsetButton from "../components/InsetButton";
import { Lightning } from "@phosphor-icons/react";
import IconEyebrow from "../components/IconEyebrow";

const inter = Inter({ subsets: ["latin"] });

type StatsProps = {
  value: string;
  subtitle: string;
};

function Stats({ value, subtitle }: StatsProps): JSX.Element {
  return (
    <div className="flex flex-col gap-2 max-w-[240px] self-start">
      <h1 className="text-white text-3xl font-medium">{value}</h1>
      <p className="text-slate-11">{subtitle}</p>
    </div>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`gap-12 ${styles.main}`}>
        <header className="fixed left-0 top-0 w-full bg-opacity-50 px-12 py-4 backdrop-blur-lg backdrop-filter z-40">
          <nav className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 z-40">
            <div className="flex h-16 items-center justify-between">
              <div className="flex-shrink-0">
                <Image
                  width="112"
                  height="29"
                  src="/images/logo.svg"
                  alt="Logo"
                />
              </div>
              <div className="hidden md:block">
                <div className="ml-10 flex items-baseline space-x-4">
                  {["Company", "Pricing", "Blog", "Use Cases"].map(
                    (text, index) => (
                      <a
                        key={index}
                        href="#"
                        className="text-md font-sm rounded-md px-3 py-2 text-slate-10 transition-colors duration-300 ease-in-out hover:text-white"
                      >
                        {text}
                      </a>
                    )
                  )}
                </div>
              </div>
              <InsetButton
                bgColor={`var(--slate1)`}
                href={`https://google.com`}
                text={`Sign in`}
                target={`_blank`}
                highlightValue={"0.2"}
              />
            </div>
          </nav>
        </header>

        <h1
          className="font-regular text-[48px] text-white pt-8"
          style={{
            backgroundImage: 'url("images/hero_text_gradient_mask_v6.svg")',
            backgroundPosition: "bottom",
            WebkitBackgroundClip: "text",
            MozBackgroundClip: "text",
            backgroundClip: "text",
            color: "transparent",
          }}
        >
          The ultimate data browser
        </h1>
        <div>
          <div className={`relative ${styles.perspectiveDiv} z-20`}>
            {/* <ThreeDiv> */}
            {/* Hero */}
            <div className={`px-2 py-2 ${styles.heroImageContainerOuter}`}>
              <div className={`px-2 py-2 ${styles.heroImageContainer}`}>
                <Image
                  className="relative z-20 m-auto pointer-events-none select-none"
                  src="/images/dataland_hero.svg"
                  alt="Hero Image"
                  draggable="false"
                  width="1053"
                  height="513"
                />
              </div>
              <div
                className={`absolute z-20 text-white ${styles.rayOfLightTop}`}
              ></div>
              <div
                className={`absolute z-20 text-white ${styles.rayOfLightBottom}`}
              ></div>
            </div>
            {/* </ThreeDiv> */}
          </div>
          <div
            className={`absolute pt-[600px] inset-0 z-30 m-auto w-full text-center text-white ${styles.heroTextContainer}`}
          >
            <h2>
              We loaded every HN post and comment, 1.6 billion rows, into this
              table.
            </h2>
            <h2>Try running search for “rust” or your HN username.</h2>

            <button
              className={`mt-4 inline-block bg-[#4315F3] py-2 px-6 w-auto rounded-full hover:bg-[#3A16C7] hover:transition-all ${styles.insetButton}`}
            >
              Launch playground
            </button>
          </div>
          <div
            className={`absolute inset-0 pointer-events-none select-none pt-[640px] z-10 w-[2700px]`}
            style={{
              left: "50%",
              transform: "translate(-50%, -12%)",
              animation: "fadeIn 0.4s ease-in-out",
              animationDelay: "1.8s",
              animationFillMode: "forwards",
              opacity: 0,
            }}
          >
            <Image
              src="/images/colored_gridlines.svg"
              alt="Hero Image"
              draggable="false"
              width="3000"
              height="600"
            />
          </div>
        </div>
        <div
          className="max-w-lg text-white z-20 flex flex-col gap-4 py-12"
          style={{
            animation: "fadeInFromBottom 0.4s ease-in-out",
            animationDelay: "2.4s",
            animationFillMode: "forwards",
            opacity: 0,
          }}
        >
          <h2 className="text-xl">
            Dataland is a new kind of data browser that delivers a seamless user
            experience, regardless of data scale.{" "}
          </h2>
          <p className="text-slate-11">
            Dataland lets your internal teams access the data in your data
            warehouse using a familiar spreadsheet-like UI that works the same
            way across 10 rows or 10,000,000,000 rows.{" "}
          </p>
          <p className="text-slate-11">
            Billion row tables load instantly, straight from your web browser.
            Gone are the days of waiting for loading spinners, clicking through
            50 rows per page, and being limited by pre-defined query patterns.
          </p>
          <div className="flex flex-row gap-4 pt-4 items-center">
            <InsetButton
              bgColor={`#4315F3`}
              href={`https://google.com`}
              text={`Get started`}
              target={`_blank`}
              highlightValue={"0.5"}
            />
            <p className="text-white"> $5 per GB-month • Unlimited users</p>
          </div>
        </div>
        <div className="w-[1100px] space-y-36">
          <div className="text-white flex flex-row gap-12">
            <Image
              className="relative z-20 m-auto pointer-events-none select-none"
              src="/images/logos/logo_wyndly.svg"
              alt="Wyndly"
              draggable="false"
              width="120"
              height="120"
            />
            <Image
              className="relative z-20 m-auto pointer-events-none select-none"
              src="/images/logos/logo_gorgias.svg"
              alt="Gorgias"
              draggable="false"
              width="120"
              height="120"
            />
            <Image
              className="relative z-20 m-auto pointer-events-none select-none"
              src="/images/logos/logo_wyndly.svg"
              alt="Wyndly"
              draggable="false"
              width="120"
              height="120"
            />
            <Image
              className="relative z-20 m-auto pointer-events-none select-none"
              src="/images/logos/logo_gorgias.svg"
              alt="Gorgias"
              draggable="false"
              width="120"
              height="120"
            />
          </div>
          <div className=" text-white z-20 flex flex-row gap-16 items-center">
            <Image
              className="relative z-20 m-auto pointer-events-none select-none w-2/3"
              src="/images/performance_diagram.svg"
              alt="Hero Image"
              draggable="false"
              width="1053"
              height="513"
            />
            <div className="flex flex-col gap-4">
              <IconEyebrow
                icon={<Lightning color="#E5C3F0" />}
                text="Performance"
              />
              <h2 className="text-xl">
                Leveraging WebGL, WASM, and Rust for ultra-high performance
              </h2>
              <p className="text-slate-11">
                The data source API handles automatic caching from selected
                datasets in your data warehouse.
              </p>
              <p className="text-slate-11">
                The indexing and caching layer is optimized for data loading and
                full-text search.
              </p>
              <p className="text-slate-11">
                The UI works with the caching layer to seamlessly translate user
                action (scrolling, searching, etc.) to give instant results on
                the front-end.
              </p>
            </div>
          </div>
          <div className="flex flex-row gap-12 justify-evenly">
            <Stats value="<1s" subtitle="Load time for 1 billion rows" />
            <Stats value="0.1s" subtitle="table load times" />
            <Stats
              value="133x faster"
              subtitle="for searches compared to Retool querying directly from Snowflake"
            />
            <Stats
              value="98x cheaper"
              subtitle="for searches compared to querying directly from Snowflake"
            />
          </div>
          <div className="flex flex-col gap-12 py-16 border-t border-b border-slate-3 items-center">
            <div className="flex flex-row text-white items-center gap-24">
              <h1 className="text-3xl w-[240px]">
                Full-text search that just works
              </h1>
              <p className="text-md max-w-xl">
                Just ⌘F to launch a case insensitive, substring search that
                returns results instantly. Instantly jump to the next search
                result a million rows away.
              </p>
            </div>
            <div>
              <Image
                className="relative pointer-events-none select-none"
                src="/images/product_search.svg"
                alt="Product Screenshot - Search"
                draggable="false"
                width="1000"
                height="378"
              />
            </div>
          </div>
          <div className="flex flex-col gap-12 items-center">
            <div className="flex flex-col text-white items-center gap-12">
              <h1 className="text-3xl w-[240px]">Rich cell types</h1>
              <p className="text-md max-w-xl">
                Rich cell types help users understand data, faster.
              </p>{" "}
              <p>
                We auto-assign the right cell type based on column contents.
              </p>
            </div>
            <div>
              <Image
                className="relative pointer-events-none select-none"
                src="/images/product_rich_cells.svg"
                alt="Product Screenshot - Rich Cell Types"
                draggable="false"
                width="1100"
                height="489"
              />
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
