import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import GradientBorder from "../components/GradientBorder";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`gap-12 ${styles.main}`}>
        <header className="fixed left-0 top-0 w-full bg-opacity-50 px-12 py-4 backdrop-blur-lg backdrop-filter">
          <nav className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <div className="flex h-16 items-center justify-between">
              <div className="flex-shrink-0">
                <img className="w-28" src="/images/logo.svg" alt="Logo" />
              </div>
              <div className="hidden md:block">
                <div className="ml-10 flex items-baseline space-x-4">
                  {["Company", "Pricing", "Blog", "Use Cases"].map(
                    (text, index) => (
                      <a
                        key={index}
                        href="#"
                        className="text-md font-sm rounded-md px-3 py-2 text-white/50 transition-colors duration-300 ease-in-out hover:text-white"
                      >
                        {text}
                      </a>
                    )
                  )}
                </div>
              </div>
              <div className="hidden md:block">
                <div>
                  <a
                    href="#"
                    className={`text-md inset-border rounded-full bg-slate-1 px-3 py-2 text-sm font-medium text-white ${styles.insetBorder}`}
                  >
                    Sign In
                  </a>
                </div>
              </div>
            </div>
          </nav>
        </header>

        <h1 className="font-regular text-[48px] text-white">
          The ultimate data browser
        </h1>
        <div className="relative">
          <img
            className="relative z-20 "
            src="/images/dataland_hero.svg"
            alt="Hero Image"
          />
          <img
            className="absolute inset-0 z-10 m-auto"
            src="/images/gradients_hero.svg"
            alt="Gradients"
          />
        </div>
        <GradientBorder>
          <div
            style={{
              margin: "20px",
              padding: "20px",
              backgroundColor: "#FFFFFF20",
            }}
          >
            Content goes here
          </div>
        </GradientBorder>
        <button className="bg-gray-800 px-4 py-3 text-white">Button</button>
      </main>
    </>
  );
}
