import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import React, { useState } from "react";
import Link from "next/link";
import LoaderAnimation from "../components/LoaderAnimation";

const inter = Inter({ subsets: ["latin"] });

export default function Sandbox() {
  return (
    <>
      <Head>
        <title>Dataland</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>
      <main
        className={`overflow-hidden flex h-screen flex-row justify-center items-center min-h-screen bg-slate-1`}
      >
        <div className="w-full flex flex-row flex-grow h-screen">
          <div className="w-full flex justify-center border-r border-slate-3">
            <div className="w-[600px] text-white flex flex-col items-start justify-center left-0 py-3 gap-2 sm:px-24 px-12 h-screen">
              <div className="flex flex-col flex-grow justify-end text-center">
                <h3 className="text-xs text-slate-9"></h3>
              </div>
              <h1 className="text-xl ">Welcome back</h1>
              <h3 className="text-sm text-slate-11">Log into Dataland</h3>
              <div className="flex flex-col gap-4 mt-8 w-full">
                <div className="w-full flex flex-col gap-2">
                  <button className="w-full bg-slate-3 border border-slate-6 text-white text-sm font-medium rounded-md px-4 py-2 flex flex-row gap-3 hover:bg-slate-4 justify-center">
                    <Image
                      src="/images/logo_google.svg"
                      width={24}
                      height={24}
                      alt="Google logo"
                    ></Image>
                    Sign up with Google
                  </button>
                  <button className="w-full bg-slate-3 border border-slate-6 text-white text-sm font-medium rounded-md px-4 py-2 flex flex-row gap-3 hover:bg-slate-4 justify-center">
                    <Image
                      src="/images/logo_github.svg"
                      width={24}
                      height={24}
                      alt="Google logo"
                    ></Image>
                    Sign up with GitHub
                  </button>
                </div>
                <div className="flex flex-row items-center justify-center">
                  <hr className="w-full border-1 border-slate-6" />
                  <div className="mx-2 text-slate-11 text-sm">or</div>
                  <hr className="w-full border-1 border-slate-6" />
                </div>
                {/* Write a form input compoennt */}
                <div className="flex flex-col gap-2">
                  <div className="flex flex-col gap-2">
                    <label
                      htmlFor="email"
                      className="text-white text-sm font-medium"
                    >
                      Email
                    </label>
                    <input
                      id="email"
                      className="bg-slate-3 hover:bg-slate-4 border border-slate-6 text-white text-sm font-medium rounded-md px-4 py-2 placeholder-slate-9"
                      type="email"
                      placeholder="you@company.com"
                    />
                    {/* Add a password field */}
                    <label
                      htmlFor="password"
                      className="text-white text-sm font-medium mt-2"
                    >
                      Password
                    </label>
                    <input
                      id="password"
                      className="bg-slate-3 hover:bg-slate-4 border border-slate-6 text-white text-sm font-medium rounded-md px-4 py-2 placeholder-slate-9"
                      type="password"
                      placeholder="•••••••••••••"
                    />
                  </div>
                </div>
                <button className="bg-blue-600 text-white text-sm font-medium rounded-md px-4 py-2 flex flex-row gap-3 hover:bg-blue-700 justify-center h-10 items-center">
                  Log in
                </button>
              </div>
              <h3 className="text-sm text-slate-11 mt-8 w-full items-center text-center">
                Don&apos;t have an account yet?{" "}
                <Link href="/signup" className="text-blue-500">
                  {" "}
                  Sign up here.
                </Link>
              </h3>
              <div className="flex flex-col flex-grow justify-end text-center"></div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
