import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import React, { useState } from "react";
import Link from "next/link";
import Footer from "../components/Footer";
import Header from "../components/Header";
import LogoSvgAnimation from "../components/LogoSvgAnimation";

const inter = Inter({ subsets: ["latin"] });

export default function Sandbox() {
  return (
    <>
      <Head>
        <title>Dataland 1B: Sandbox</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={` ${styles.main} h-screen px-4 overflow-hidden`}>
        {/* Add an input that changes the value of heroType */}

        <Header />
        {/* This option is the header + two-line subheader with DWH logos */}

        <div className="text-white h-full">Hello </div>
        <LogoSvgAnimation />

        <Footer />
      </main>
    </>
  );
}
