import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import React, { useState } from "react";
import Link from "next/link";
import LoaderAnimation from "../components/LoaderAnimation";

const inter = Inter({ subsets: ["latin"] });

export default function Sandbox() {
  return (
    <>
      <Head>
        <title>Dataland</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`overflow-hidden flex h-screen flex-col justify-center items-center min-h-screen bg-slate-1`}
      >
        <div className="w-full flex flex-row flex-grow">
          <div className="w-2/5 text-white flex flex-col items-start justify-center left-0 border-r border-slate-6 py-3 gap-2 px-24">
            <h1 className="text-xl ">Try Dataland for free</h1>
            <h3 className="text-sm text-slate-11">Create a new account</h3>
            <div className="flex flex-col gap-2 mt-8 w-full">
              <button className="bg-slate-3 border border-slate-6 text-white text-sm font-medium rounded-md px-4 py-2 flex flex-row gap-3 hover:bg-slate-4 justify-center">
                <Image
                  src="/images/logo_google.svg"
                  width={24}
                  height={24}
                  alt="Google logo"
                ></Image>
                Sign up with Google
              </button>
              <button className="bg-slate-3 border border-slate-6 text-white text-sm font-medium rounded-md px-4 py-2 flex flex-row gap-3 hover:bg-slate-4 justify-center">
                <Image
                  src="/images/logo_github.svg"
                  width={24}
                  height={24}
                  alt="Google logo"
                ></Image>
                Sign up with GitHub
              </button>
              <div className="flex flex-row items-center justify-center">
                <hr className="w-full border-1 border-slate-6" />
                <div className="mx-2 text-slate-11 text-sm">or</div>
                <hr className="w-full border-1 border-slate-6" />
              </div>
              {/* Write a form input compoennt */}
              <div className="flex flex-col gap-2">
                <div className="flex flex-col gap-1">
                  <label className="text-slate-11 text-sm">Email</label>
                  <input
                    className="bg-slate-3 border border-slate-6 text-white text-sm font-medium rounded-md px-4 py-2"
                    type="email"
                  />
                  {/* Make a password field too */}
                  <label className="text-slate-11 text-sm">Password</label>
                  <input
                    className="bg-slate-3 border border-slate-6 text-white text-sm font-medium rounded-md px-4 py-2"
                    type="password"
                  />
                </div>
              </div>
            </div>
          </div>
          <div className="w-3/5 z-30 flex flex-col gap-6 items-center top-96 justify-center">
            <div>
              <h1 className="text-slate-9">Loading rows..</h1>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
