import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import React, { useState } from "react";
import Link from "next/link";
import { CircleNotch, CheckCircle } from "@phosphor-icons/react";

const inter = Inter({ subsets: ["latin"] });

export default function Login() {
  const [loading, setLoading] = useState(false);
  const [emailSent, setEmailSent] = useState(false);

  const handleSubmit = async (event: any) => {
    event.preventDefault();
    setEmailSent(false);
    setLoading(true); // Set loading to true before the delay

    await Promise.all([
      new Promise<void>((resolve) => {
        setTimeout(() => {
          setLoading(false); // Set loading back to false after the delay
          resolve();
        }, 1500);
      }),
      new Promise<void>((resolve) => {
        // Call mock API to send email here
        resolve();
      }),
    ]);
    setLoading(false);
    setEmailSent(true); // Set emailSent to true after both Promises have resolved
  };

  return (
    <>
      <Head>
        <title>Dataland</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>
      <main
        className={`overflow-hidden flex h-screen flex-row justify-center items-center min-h-screen bg-slate-1`}
      >
        <div className="w-full flex flex-row flex-grow h-screen">
          <div className="w-full flex justify-center border-r border-slate-3">
            <div className="w-[600px] text-white flex flex-col pt-40 left-0 py-3 gap-2 sm:px-24 px-12 h-screen">
              <header className="fixed top-8">
                <Link href="/">
                  <Image
                    src="/images/logo_darker.svg"
                    width={80}
                    height={32}
                    alt="Dataland logo"
                  ></Image>
                </Link>
              </header>
              <div className="gap-4 flex flex-col">
                <h1 className="text-lg flex flex-row gap-2 items-center">
                  Check your inbox to verify account
                </h1>

                <p className="text-sm text-slate-11">
                  Just one more step! Check your email for a link to verify your
                  account. Then, you can finish logging into Dataland.
                </p>
              </div>
              <div className="flex flex-col gap-4">
                {/* Write a form input compoennt */}
                <form onSubmit={handleSubmit}>
                  <div className="flex flex-row items-center gap-2  mt-4">
                    <button
                      className={`bg-slate-3 text-white text-sm font-medium rounded-md px-4 py-2 gap-3 hover:bg-slate-4 justify-center h-10 items-center self-start flex flex-row
                      ${loading ? "opacity-50 hover:bg-blue-600" : ""}`}
                      type="submit"
                      disabled={loading}
                    >
                      {loading ? (
                        <>
                          <span className="animate-spin">
                            <CircleNotch width={20} height={20} />
                          </span>
                          <span>Sending..</span>
                        </>
                      ) : (
                        "Send again"
                      )}
                    </button>
                    {emailSent && (
                      <>
                        <CheckCircle
                          width={24}
                          height={24}
                          className="text-green-500"
                        />
                        <p className="text-sm text-slate-11">
                          Email sent! Check your inbox.
                        </p>
                      </>
                    )}
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
